I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 25, in script
    define r = Character("Robin", callback=r)
  File "game/script.rpy", line 25, in <module>
    define r = Character("Robin", callback=r)
NameError: name 'r' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 25, in script
    define r = Character("Robin", callback=r)
  File "/home/ali-brooks/renpy-8.1.1-sdk/renpy/ast.py", line 2508, in execute
    self.set()
  File "/home/ali-brooks/renpy-8.1.1-sdk/renpy/ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/home/ali-brooks/renpy-8.1.1-sdk/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 25, in <module>
    define r = Character("Robin", callback=r)
NameError: name 'r' is not defined

Linux-5.19.0-45-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.1.1.23060707
First Day 1.0
Fri Jul 14 03:00:35 2023
